Traceback (most recent call last):
  File "/Users/seanwalsh/Documents/Github-Mac-Laptop/philstatsbook/.venv/lib/python3.12/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/seanwalsh/Documents/Github-Mac-Laptop/philstatsbook/.venv/lib/python3.12/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/seanwalsh/Documents/Github-Mac-Laptop/philstatsbook/.venv/lib/python3.12/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/base_events.py", line 664, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/seanwalsh/Documents/Github-Mac-Laptop/philstatsbook/.venv/lib/python3.12/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/Users/seanwalsh/Documents/Github-Mac-Laptop/philstatsbook/.venv/lib/python3.12/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/seanwalsh/Documents/Github-Mac-Laptop/philstatsbook/.venv/lib/python3.12/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
Binomvisualbothtypes(10,.4,.6)
Binomvisualbothtypes(20,.4,.6)
Binomvisualbothtypes(50,.4,.6)
Binomvisualbothtypes(100,.4,.6)
Binomvisualbothtypes(1000,.4,.6)
Binomvisualbothtypes(100000,.4,.6)

Binombothtypes(10,.4,.6)
Binombothtypes(20,.4,.6)
Binombothtypes(50,.4,.6)
Binombothtypes(100,.4,.6)
Binombothtypes(1000,.4,.6)
Binombothtypes(100000,.4,.6)
------------------

----- stderr -----
/var/folders/xw/hl5lcyld76q3j0w5861p6yjm0000gq/T/ipykernel_91299/325915012.py:54: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  axs[1].axvline(x=cvX, color='c', linestyle='--', label = '%1.2f' % cvX)
/var/folders/xw/hl5lcyld76q3j0w5861p6yjm0000gq/T/ipykernel_91299/325915012.py:65: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  axs[2].axvline(x=cvY, color='c', linestyle='--', label = '%1.2f' % cvY)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[9], line 8[0m
[1;32m      5[0m Binomvisualbothtypes([38;5;241m1000[39m,[38;5;241m.4[39m,[38;5;241m.6[39m)
[1;32m      6[0m Binomvisualbothtypes([38;5;241m100000[39m,[38;5;241m.4[39m,[38;5;241m.6[39m)
[0;32m----> 8[0m [43mBinombothtypes[49m([38;5;241m10[39m,[38;5;241m.4[39m,[38;5;241m.6[39m)
[1;32m      9[0m Binombothtypes([38;5;241m20[39m,[38;5;241m.4[39m,[38;5;241m.6[39m)
[1;32m     10[0m Binombothtypes([38;5;241m50[39m,[38;5;241m.4[39m,[38;5;241m.6[39m)

[0;31mNameError[0m: name 'Binombothtypes' is not defined

